"""
Django settings for quizscan project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Données persistantes (base SQLite) — montées en volume sous Docker
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#kjj&b*aq8$znhb4_(agf6d^v=6m%-ke)w@ahfyuy)+*e3m7s2"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "grader",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "quizscan.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "quizscan.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_DIR / "db.sqlite3",
        # la correction des lots tourne en arrière-plan pendant que
        # l'enseignant navigue : on patiente au lieu d'échouer sur un verrou
        "OPTIONS": {"timeout": 30},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "Africa/Tunis"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# ---------------------------------------------------------------------------
# Configuration par variables d'environnement (déploiement Docker / Caddy).
#   SECRET_KEY           clé secrète de production (obligatoire si DEBUG=0)
#   DEBUG                "0" en production
#   ALLOWED_HOSTS        hôtes autorisés, séparés par des virgules
#   CSRF_TRUSTED_ORIGINS origines https de confiance, séparées par des virgules
#   URL_PREFIX           sous-chemin derrière le reverse proxy (ex. /quizscan)
#   HTTPS                "0" si l'application est jointe en http:// (réseau local)
#   POSTGRES_*           base PostgreSQL au lieu de SQLite (usage intensif)
# ---------------------------------------------------------------------------
import os  # noqa: E402

from django.core.exceptions import ImproperlyConfigured  # noqa: E402

INSECURE_DEV_SECRET_KEY = SECRET_KEY
SECRET_KEY = os.environ.get("SECRET_KEY") or INSECURE_DEV_SECRET_KEY
DEBUG = os.environ.get("DEBUG", "1") not in ("0", "false", "False", "no")
if os.environ.get("ALLOWED_HOSTS"):
    ALLOWED_HOSTS = [h.strip() for h in os.environ["ALLOWED_HOSTS"].split(",")]
if os.environ.get("CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in
                            os.environ["CSRF_TRUSTED_ORIGINS"].split(",")]

# En production, refuser de démarrer avec la clé de développement (publiée
# dans le dépôt) : elle signe les sessions et les jetons CSRF. Le message
# indique quoi faire plutôt que de laisser l'installation vulnérable.
if not DEBUG and SECRET_KEY == INSECURE_DEV_SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY n'est pas définie : l'application refuse de démarrer en "
        "production avec la clé de développement du dépôt. Renseignez "
        "SECRET_KEY dans le fichier .env (cp .env.example .env), par exemple "
        "avec : python3 -c \"import secrets; print(secrets.token_urlsafe(50))\"")

# En production, ALLOWED_HOSTS=["*"] laisse passer n'importe quel en-tête Host
# (empoisonnement des liens de réinitialisation, cache). On exige la liste.
if not DEBUG and ALLOWED_HOSTS == ["*"]:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS n'est pas définie : indiquez dans .env les noms d'hôte "
        "par lesquels l'application est joignable, séparés par des virgules "
        "(ex. ALLOWED_HOSTS=mon-domaine.tn,192.168.1.10).")

# ---------------------------------------------------------------------------
# Base de données : SQLite (fichier unique sous data/) par défaut, ou
# PostgreSQL pour un usage intensif — il suffit de renseigner POSTGRES_DB,
# POSTGRES_USER et POSTGRES_PASSWORD (POSTGRES_HOST/PORT facultatifs).
# ---------------------------------------------------------------------------
if os.environ.get("POSTGRES_DB"):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ.get("POSTGRES_USER", "quizscan"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }

# Sous-chemin (ex. /quizscan) : le proxy retire le préfixe (uri strip_prefix)
# et FORCE_SCRIPT_NAME le rajoute dans toutes les URLs générées par Django.
URL_PREFIX = os.environ.get("URL_PREFIX", "").rstrip("/")
if URL_PREFIX:
    FORCE_SCRIPT_NAME = URL_PREFIX
STATIC_URL = f"{URL_PREFIX}/static/"
MEDIA_URL = f"{URL_PREFIX}/media/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Derrière Caddy en HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ---------------------------------------------------------------------------
# Durcissement en production. L'application sert des données nominatives
# (copies scannées, notes, bulletins) : les cookies de session et CSRF ne
# doivent circuler qu'en HTTPS (assuré par le reverse proxy) et rester
# inaccessibles au JavaScript tiers.
# ---------------------------------------------------------------------------
if not DEBUG:
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    X_FRAME_OPTIONS = "DENY"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"

    # HTTPS=1 (défaut) : les cookies de session et CSRF sont marqués
    # « Secure », le navigateur ne les renvoie donc que sur https://.
    # Si l'application est jointe en http:// — accès direct par l'adresse IP
    # sur un réseau local, sans reverse proxy TLS — il faut HTTPS=0, sinon le
    # navigateur refuse de renvoyer le cookie et la connexion boucle sans
    # message d'erreur. À ne faire que sur un réseau de confiance.
    HTTPS = os.environ.get("HTTPS", "1") not in ("0", "false", "False", "no")
    SESSION_COOKIE_SECURE = HTTPS
    CSRF_COOKIE_SECURE = HTTPS
    # Redirection http -> https : assurée par le reverse proxy. Si ce n'est
    # pas le cas chez vous, passez SECURE_SSL_REDIRECT=1.
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "0") == "1"

# Journalisation : la correction tourne en arrière-plan (threads), ses
# erreurs doivent apparaître dans les journaux du conteneur
# (docker compose logs quizscan) et non se perdre.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "{asctime} {levelname} {name} {message}",
                   "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "ERROR",
                           "propagate": False},
        "grader": {"handlers": ["console"], "level": "INFO",
                   "propagate": False},
    },
}

# Tests automatiques (test_e2e*.py) : base et documents séparés, pour ne
# jamais créer de comptes ni de copies de test dans la base de production.
if os.environ.get("QUIZSCAN_TEST"):
    if DATABASES["default"]["ENGINE"].endswith("sqlite3"):
        DATABASES["default"]["NAME"] = DATA_DIR / "test_db.sqlite3"
    MEDIA_ROOT = BASE_DIR / "media_test"
