# Generated by Django 5.2.17 on 2026-08-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Nom de la classe"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Classe",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "num_choices",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Ex. 4 pour A, B, C, D",
                        verbose_name="Nombre de choix par question QCM",
                    ),
                ),
                (
                    "wrong_penalty",
                    models.FloatField(
                        default=0.0,
                        help_text="Points retirés pour chaque mauvaise réponse QCM (0 = pas de pénalité)",
                        verbose_name="Pénalité par mauvaise réponse",
                    ),
                ),
                (
                    "layout_json",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "sheet_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sheets/",
                        verbose_name="Fiche de réponses (PDF)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quizzes",
                        to="grader.classgroup",
                        verbose_name="Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(verbose_name="N°")),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("qcm", "QCM (lecture automatique)"),
                            ("open", "Réponse manuscrite (correction manuelle)"),
                        ],
                        default="qcm",
                        max_length=4,
                        verbose_name="Type",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Intitulé (optionnel)"
                    ),
                ),
                (
                    "points",
                    models.FloatField(default=1.0, verbose_name="Barème (points)"),
                ),
                (
                    "correct_choice",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Bonne réponse"
                    ),
                ),
                (
                    "open_height_mm",
                    models.PositiveSmallIntegerField(
                        default=25, verbose_name="Hauteur zone réponse (mm)"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="grader.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "ordering": ["order"],
                "unique_together": {("quiz", "order")},
            },
        ),
        migrations.CreateModel(
            name="ScanBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Libellé"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="grader.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot de scans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=80, verbose_name="Nom")),
                ("first_name", models.CharField(max_length=80, verbose_name="Prénom")),
                (
                    "student_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="N° d'inscription"
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="grader.classgroup",
                        verbose_name="Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étudiant",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="SheetScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_index",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Page de la fiche"
                    ),
                ),
                ("source_name", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(upload_to="scans/")),
                (
                    "warped_image",
                    models.ImageField(blank=True, null=True, upload_to="warped/"),
                ),
                (
                    "overlay_image",
                    models.ImageField(blank=True, null=True, upload_to="overlays/"),
                ),
                (
                    "name_crop",
                    models.ImageField(blank=True, null=True, upload_to="crops/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("ok", "Lu avec succès"),
                            ("no_markers", "Repères non détectés"),
                            ("no_match", "Étudiant non identifié"),
                            ("error", "Erreur"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "ocr_name_raw",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom lu (OCR)"
                    ),
                ),
                ("match_score", models.FloatField(default=0.0)),
                (
                    "student_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="Identification confirmée"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="grader.scanbatch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sheets",
                        to="grader.student",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page scannée",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_choice", models.SmallIntegerField(blank=True, null=True)),
                ("is_multiple", models.BooleanField(default=False)),
                ("fill_ratios", models.JSONField(blank=True, null=True)),
                (
                    "open_crop",
                    models.ImageField(blank=True, null=True, upload_to="crops/"),
                ),
                (
                    "points_awarded",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Points attribués"
                    ),
                ),
                ("manually_set", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="grader.question",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="grader.sheetscan",
                    ),
                ),
            ],
            options={
                "ordering": ["question__order"],
                "unique_together": {("sheet", "question")},
            },
        ),
    ]
