# Generated by Django 5.2.17 on 2026-08-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="language",
            field=models.CharField(
                choices=[("fr", "Français"), ("ar", "العربية (arabe)")],
                default="fr",
                help_text="Détermine la langue de la fiche de réponses (sens d'écriture, lettres des choix) et de la lecture OCR du nom.",
                max_length=2,
                verbose_name="Langue du questionnaire",
            ),
        ),
    ]
