# Generated by Django 5.2.17 on 2026-08-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0002_quiz_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="choices",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Choix de réponse"
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="sheet_mode",
            field=models.CharField(
                choices=[
                    (
                        "full",
                        "Questionnaire complet — les questions et leurs choix sont imprimés sur la fiche",
                    ),
                    (
                        "grid",
                        "Fiche de réponses seule — grille compacte, le sujet est distribué à part",
                    ),
                ],
                default="full",
                max_length=4,
                verbose_name="Type de fiche",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Intitulé de la question"
            ),
        ),
    ]
