# Generated by Django 5.2.17 on 2026-08-28 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0003_question_choices_quiz_sheet_mode_alter_question_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Enseignant",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="id_digits",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 = pas de grille. Sinon (ex. 6), une grille de chiffres à noircir est imprimée sur la fiche : identification 100 % fiable à partir du n° d'inscription des étudiants.",
                verbose_name="Chiffres du n° d'inscription",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Enseignant",
            ),
        ),
        migrations.AddField(
            model_name="sheetscan",
            name="id_read",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="N° d'inscription lu"
            ),
        ),
        migrations.AlterField(
            model_name="classgroup",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Nom de la classe"),
        ),
        migrations.AlterUniqueTogether(
            name="classgroup",
            unique_together={("owner", "name")},
        ),
    ]
