# Generated by Django 5.2.17 on 2026-09-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0004_classgroup_owner_quiz_id_digits_quiz_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="id_mode",
            field=models.CharField(
                choices=[
                    (
                        "name",
                        "OCR du nom manuscrit (fiches identiques pour toute la classe)",
                    ),
                    (
                        "grid",
                        "Grille de n° d'inscription à noircir (fiches identiques, lecture exacte)",
                    ),
                    (
                        "qr",
                        "QR code — fiches nominatives pré-imprimées (une fiche par étudiant, identification instantanée et infaillible)",
                    ),
                ],
                default="name",
                max_length=4,
                verbose_name="Identification des copies",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="id_digits",
            field=models.PositiveSmallIntegerField(
                default=6,
                help_text="Utilisé uniquement avec la grille : nombre de chiffres du numéro d'inscription (ex. 6).",
                verbose_name="Chiffres du n° d'inscription",
            ),
        ),
    ]
