# Generated by Django 5.2.17 on 2026-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0006_id_mode_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="auto_enroll",
            field=models.BooleanField(
                default=False,
                help_text="Aucune saisie préalable des étudiants : chaque copie scannée crée son candidat à partir du numéro lu (grille ou QR de fiche anonyme), avec le nom lu par OCR. Vous pouvez ensuite importer une liste « numéro;NOM;Prénom » pour compléter les noms.",
                verbose_name="Mode concours : créer automatiquement les candidats",
            ),
        ),
    ]
