# Generated by Django 5.2.17 on 2026-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0007_quiz_auto_enroll"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="subject_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="sheets/",
                verbose_name="Sujet — questions (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="sheet_mode",
            field=models.CharField(
                choices=[
                    (
                        "full",
                        "Questionnaire complet — les questions et leurs choix sont imprimés sur la fiche",
                    ),
                    (
                        "split",
                        "Sujet séparé + feuille de réponses — deux documents (questions d'un côté, grille de l'autre)",
                    ),
                    (
                        "grid",
                        "Fiche de réponses seule — grille compacte, le sujet est distribué à part",
                    ),
                ],
                default="full",
                max_length=6,
                verbose_name="Type de fiche",
            ),
        ),
    ]
