# Generated by Django 5.2.17 on 2026-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0008_quiz_subject_pdf_alter_quiz_sheet_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="id_mode",
            field=models.CharField(
                choices=[
                    (
                        "name",
                        "OCR du nom manuscrit (fiches identiques pour toute la classe)",
                    ),
                    (
                        "grid",
                        "Grille de n° d'inscription à noircir (fiches identiques, lecture exacte)",
                    ),
                    (
                        "qr",
                        "QR code — fiches nominatives pré-imprimées (une fiche par étudiant, identification instantanée et infaillible)",
                    ),
                    (
                        "sticker",
                        "Zone étiquette autocollante — emplacement réservé en haut pour coller une étiquette (n° d'inscription + QR) ; identification manuelle",
                    ),
                ],
                default="name",
                max_length=8,
                verbose_name="Identification des copies",
            ),
        ),
    ]
