# Generated by Django 5.2.17 on 2026-09-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0009_alter_quiz_id_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanbatch",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scanbatch",
            name="processed_pages",
            field=models.PositiveIntegerField(default=0, verbose_name="Pages traitées"),
        ),
        migrations.AddField(
            model_name="scanbatch",
            name="source_files",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name="scanbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Correction en cours"),
                    ("done", "Terminé"),
                    ("error", "Erreur"),
                ],
                default="done",
                max_length=12,
                verbose_name="État",
            ),
        ),
        migrations.AddField(
            model_name="scanbatch",
            name="total_pages",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Pages à traiter"
            ),
        ),
        migrations.AddField(
            model_name="scanbatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="id_mode",
            field=models.CharField(
                choices=[
                    (
                        "name",
                        "OCR du nom manuscrit (fiches identiques pour toute la classe)",
                    ),
                    (
                        "grid",
                        "Grille de n° d'inscription à noircir (fiches identiques, lecture exacte)",
                    ),
                    (
                        "qr",
                        "QR code — fiches nominatives pré-imprimées (une fiche par étudiant, identification instantanée et infaillible)",
                    ),
                    (
                        "sticker",
                        "QR code — étiquette autocollante par candidat (planche d'étiquettes à coller dans l'emplacement réservé ; lue automatiquement au scan)",
                    ),
                ],
                default="name",
                max_length=8,
                verbose_name="Identification des copies",
            ),
        ),
    ]
