# Generated by Django 5.2.17 on 2026-10-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0010_batch_progress_sticker_qr"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="num_choices",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Nombre de cases A, B, C… de cette question (si le texte des choix n'est pas saisi).",
                null=True,
                verbose_name="Nombre de choix",
            ),
        ),
    ]
