# Generated by Django 5.2.17 on 2026-10-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0011_question_num_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="grading_mode",
            field=models.CharField(
                choices=[
                    (
                        "immediate",
                        "Correction immédiate — chaque lot est corrigé dès son téléversement",
                    ),
                    (
                        "deferred",
                        "Correction après scan — on téléverse toutes les copies, puis on clique sur « Lancer la correction »",
                    ),
                ],
                default="immediate",
                max_length=10,
                verbose_name="Correction des copies",
            ),
        ),
        migrations.AlterField(
            model_name="scanbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente de correction"),
                    ("processing", "Correction en cours"),
                    ("done", "Terminé"),
                    ("error", "Erreur"),
                ],
                default="done",
                max_length=12,
                verbose_name="État",
            ),
        ),
    ]
