# Generated by Django 5.2.18 on 2026-10-07 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0012_grading_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='num_choices',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre de cases A, B, C… de cette question (si le texte des choix n'est pas saisi) ; 2 à 10.", null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de choix'),
        ),
        migrations.AlterField(
            model_name='question',
            name='open_height_mm',
            field=models.PositiveSmallIntegerField(default=25, help_text='10 à 200 mm (une zone plus haute ne tiendrait pas sur une page A4).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)], verbose_name='Hauteur zone réponse (mm)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='auto_enroll',
            field=models.BooleanField(default=False, help_text="Aucune saisie préalable des étudiants : chaque copie scannée crée son candidat à partir du numéro lu (grille de n° ou QR de l'étiquette). La fiche concours ne demande aucune écriture au candidat ; importez ensuite une liste « numéro;NOM;Prénom » pour attacher les noms officiels aux numéros.", verbose_name='Mode concours : créer automatiquement les candidats'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='num_choices',
            field=models.PositiveSmallIntegerField(default=4, help_text='Ex. 4 pour A, B, C, D (2 à 10)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de choix par question QCM'),
        ),
    ]
