# Generated by Django 5.2.18 on 2026-10-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0013_bornes_choix_hauteur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question__order'], 'verbose_name': 'Réponse', 'verbose_name_plural': 'Réponses'},
        ),
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['name'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='scanbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lot de scans', 'verbose_name_plural': 'Lots de scans'},
        ),
        migrations.AlterModelOptions(
            name='sheetscan',
            options={'ordering': ['created_at'], 'verbose_name': 'Page scannée', 'verbose_name_plural': 'Pages scannées'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Étudiant', 'verbose_name_plural': 'Étudiants'},
        ),
    ]
