# Generated by Django 5.2.18 on 2026-10-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0014_libelles_pluriels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKeySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.PositiveSmallIntegerField(default=0, verbose_name='Page de la fiche')),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='corriges/')),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='corriges/')),
                ('status', models.CharField(choices=[('ok', 'Corrigé lu'), ('partial', 'Corrigé lu partiellement'), ('no_markers', 'Repères non détectés'), ('error', 'Erreur')], default='ok', max_length=12)),
                ('detected', models.JSONField(blank=True, default=dict)),
                ('unreadable', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key_sheets', to='grader.quiz')),
            ],
            options={
                'verbose_name': 'Corrigé scanné',
                'verbose_name_plural': 'Corrigés scannés',
                'ordering': ['-created_at', 'page_index'],
            },
        ),
    ]
