# Generated by Django 5.2.18 on 2026-10-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0015_corrige_scanne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'permissions': [('creer_epreuve', 'Créer et modifier des épreuves (quiz, concours, questions)'), ('corriger_copies', 'Téléverser les copies, lancer la correction et la vérifier')], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
    ]
