# Generated by Django 5.2.18 on 2026-10-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0017_droits_comptes_existants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='detected_choice',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Case lue'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='fill_ratios',
            field=models.JSONField(blank=True, null=True, verbose_name='Taux de remplissage'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_multiple',
            field=models.BooleanField(default=False, verbose_name='Plusieurs cases cochées'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='manually_set',
            field=models.BooleanField(default=False, verbose_name='Note saisie à la main'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='open_crop',
            field=models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='Zone manuscrite'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grader.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grader.sheetscan', verbose_name='Copie'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Scanné le'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='detected',
            field=models.JSONField(blank=True, default=dict, verbose_name='Réponses lues'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="Message d'erreur"),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='image',
            field=models.ImageField(upload_to='corriges/', verbose_name='Image scannée'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='overlay_image',
            field=models.ImageField(blank=True, null=True, upload_to='corriges/', verbose_name='Image de contrôle'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key_sheets', to='grader.quiz', verbose_name='Épreuve'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Fichier d'origine"),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='status',
            field=models.CharField(choices=[('ok', 'Corrigé lu'), ('partial', 'Corrigé lu partiellement'), ('no_markers', 'Repères non détectés'), ('error', 'Erreur')], default='ok', max_length=12, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='unreadable',
            field=models.JSONField(blank=True, default=list, verbose_name='Questions illisibles'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reçu le'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="Message d'erreur"),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='grader.quiz', verbose_name='Épreuve'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='grader.scanbatch', verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reçue le'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="Message d'erreur"),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='image',
            field=models.ImageField(upload_to='scans/', verbose_name='Image scannée'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='match_score',
            field=models.FloatField(default=0.0, verbose_name='Score de rapprochement'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='name_crop',
            field=models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='Zone du nom'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='overlay_image',
            field=models.ImageField(blank=True, null=True, upload_to='overlays/', verbose_name='Image de contrôle'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Fichier d'origine"),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('ok', 'Lu avec succès'), ('no_markers', 'Repères non détectés'), ('no_match', 'Étudiant non identifié'), ('error', 'Erreur')], default='pending', max_length=12, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='warped_image',
            field=models.ImageField(blank=True, null=True, upload_to='warped/', verbose_name='Image redressée'),
        ),
    ]
