# Generated by Django 5.2.18 on 2026-10-07 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0019_alter_classgroup_owner_alter_quiz_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quand', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('auteur_nom', models.CharField(max_length=150, verbose_name='Auteur')),
                ('action', models.CharField(choices=[('note', "Note d'une réponse"), ('case_qcm', 'Case de QCM rectifiée'), ('identification', 'Attribution de la copie'), ('bonne_reponse', 'Bonne réponse'), ('bareme', "Barème d'une question"), ('penalite', 'Pénalité par mauvaise réponse'), ('question_supprimee', 'Question supprimée'), ('copie_supprimee', 'Copie supprimée'), ('lot_supprime', 'Lot de copies supprimé')], max_length=20, verbose_name='Geste')),
                ('quiz_titre', models.CharField(blank=True, max_length=200, verbose_name='Épreuve (titre)')),
                ('objet', models.CharField(max_length=200, verbose_name='Objet')),
                ('avant', models.CharField(blank=True, max_length=200, verbose_name='Avant')),
                ('apres', models.CharField(blank=True, max_length=200, verbose_name='Après')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Compte')),
                ('copie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='grader.sheetscan', verbose_name='Copie')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='grader.quiz', verbose_name='Épreuve')),
            ],
            options={
                'verbose_name': 'Modification',
                'verbose_name_plural': 'Journal des modifications',
                'ordering': ['-quand', '-pk'],
            },
        ),
    ]
