# Generated by Django 5.2.18 on 2026-10-07 22:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0020_journal_modifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question__order'], 'verbose_name': 'réponse', 'verbose_name_plural': 'réponses'},
        ),
        migrations.AlterModelOptions(
            name='answerkeysheet',
            options={'ordering': ['-created_at', 'page_index'], 'verbose_name': 'corrigé scanné', 'verbose_name_plural': 'corrigés scannés'},
        ),
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['name'], 'verbose_name': 'classe', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='modification',
            options={'ordering': ['-quand', '-pk'], 'verbose_name': 'modification', 'verbose_name_plural': 'modifications'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'permissions': [('creer_epreuve', 'Créer et modifier des épreuves (quiz, concours, questions)'), ('corriger_copies', 'Téléverser les copies, lancer la correction et la vérifier')], 'verbose_name': 'quiz', 'verbose_name_plural': 'quiz'},
        ),
        migrations.AlterModelOptions(
            name='scanbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'lot de scans', 'verbose_name_plural': 'lots de scans'},
        ),
        migrations.AlterModelOptions(
            name='sheetscan',
            options={'ordering': ['created_at'], 'verbose_name': 'page scannée', 'verbose_name_plural': 'pages scannées'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'étudiant', 'verbose_name_plural': 'étudiants'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='detected_choice',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='case lue'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='fill_ratios',
            field=models.JSONField(blank=True, null=True, verbose_name='taux de remplissage'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_multiple',
            field=models.BooleanField(default=False, verbose_name='plusieurs cases cochées'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='manually_set',
            field=models.BooleanField(default=False, verbose_name='note saisie à la main'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='open_crop',
            field=models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='zone manuscrite'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points_awarded',
            field=models.FloatField(blank=True, null=True, verbose_name='points attribués'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grader.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='grader.sheetscan', verbose_name='copie'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='scanné le'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='detected',
            field=models.JSONField(blank=True, default=dict, verbose_name='réponses lues'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="message d'erreur"),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='image',
            field=models.ImageField(upload_to='corriges/', verbose_name='image scannée'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='overlay_image',
            field=models.ImageField(blank=True, null=True, upload_to='corriges/', verbose_name='image de contrôle'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='page_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='page de la fiche'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key_sheets', to='grader.quiz', verbose_name='épreuve'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="fichier d'origine"),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='status',
            field=models.CharField(choices=[('ok', 'Corrigé lu'), ('partial', 'Corrigé lu partiellement'), ('no_markers', 'Repères non détectés'), ('error', 'Erreur')], default='ok', max_length=12, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='answerkeysheet',
            name='unreadable',
            field=models.JSONField(blank=True, default=list, verbose_name='questions illisibles'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créée le'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nom de la classe'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to=settings.AUTH_USER_MODEL, verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='action',
            field=models.CharField(choices=[('note', "Note d'une réponse"), ('case_qcm', 'Case de QCM rectifiée'), ('identification', 'Attribution de la copie'), ('bonne_reponse', 'Bonne réponse'), ('bareme', "Barème d'une question"), ('penalite', 'Pénalité par mauvaise réponse'), ('question_supprimee', 'Question supprimée'), ('copie_supprimee', 'Copie supprimée'), ('lot_supprime', 'Lot de copies supprimé')], max_length=20, verbose_name='geste'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='apres',
            field=models.CharField(blank=True, max_length=200, verbose_name='après'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='compte'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='auteur_nom',
            field=models.CharField(max_length=150, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='avant',
            field=models.CharField(blank=True, max_length=200, verbose_name='avant'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='copie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='grader.sheetscan', verbose_name='copie'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='objet',
            field=models.CharField(max_length=200, verbose_name='objet'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='quand',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='grader.quiz', verbose_name='épreuve'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='quiz_titre',
            field=models.CharField(blank=True, max_length=200, verbose_name='épreuve (titre)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, default=list, verbose_name='choix de réponse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='bonne réponse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='num_choices',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre de cases A, B, C… de cette question (si le texte des choix n'est pas saisi) ; 2 à 10.", null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='nombre de choix'),
        ),
        migrations.AlterField(
            model_name='question',
            name='open_height_mm',
            field=models.PositiveSmallIntegerField(default=25, help_text='10 à 200 mm (une zone plus haute ne tiendrait pas sur une page A4).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)], verbose_name='hauteur zone réponse (mm)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='n°'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='barème (points)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('qcm', 'QCM (lecture automatique)'), ('open', 'Réponse manuscrite (correction manuelle)')], default='qcm', max_length=4, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=500, verbose_name='intitulé de la question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='auto_enroll',
            field=models.BooleanField(default=False, help_text="Aucune saisie préalable des étudiants : chaque copie scannée crée son candidat à partir du numéro lu (grille de n° ou QR de l'étiquette). La fiche concours ne demande aucune écriture au candidat ; importez ensuite une liste « numéro;NOM;Prénom » pour attacher les noms officiels aux numéros.", verbose_name='mode concours : créer automatiquement les candidats'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='grader.classgroup', verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créée le'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grading_mode',
            field=models.CharField(choices=[('immediate', 'Correction immédiate — chaque lot est corrigé dès son téléversement'), ('deferred', 'Correction après scan — on téléverse toutes les copies, puis on clique sur « Lancer la correction »')], default='immediate', max_length=10, verbose_name='correction des copies'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id_digits',
            field=models.PositiveSmallIntegerField(default=6, help_text="Utilisé uniquement avec la grille : nombre de chiffres du numéro d'inscription (ex. 6).", verbose_name="chiffres du n° d'inscription"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id_mode',
            field=models.CharField(choices=[('name', 'OCR du nom manuscrit (fiches identiques pour toute la classe)'), ('grid', "Grille de n° d'inscription à noircir (fiches identiques, lecture exacte)"), ('qr', 'QR code — fiches nominatives pré-imprimées (une fiche par étudiant, identification instantanée et infaillible)'), ('sticker', "QR code — étiquette autocollante par candidat (planche d'étiquettes à coller dans l'emplacement réservé ; lue automatiquement au scan)")], default='name', max_length=8, verbose_name='identification des copies'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية (arabe)')], default='fr', help_text="Détermine la langue de la fiche de réponses (sens d'écriture, lettres des choix) et de la lecture OCR du nom.", max_length=2, verbose_name='langue du questionnaire'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='num_choices',
            field=models.PositiveSmallIntegerField(default=4, help_text='Ex. 4 pour A, B, C, D (2 à 10)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='nombre de choix par question QCM'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='enseignant'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='sheet_mode',
            field=models.CharField(choices=[('full', 'Questionnaire complet — les questions et leurs choix sont imprimés sur la fiche'), ('split', "Sujet séparé + feuille de réponses — deux documents (questions d'un côté, grille de l'autre)"), ('grid', 'Fiche de réponses seule — grille compacte, le sujet est distribué à part')], default='full', max_length=6, verbose_name='type de fiche'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='sheet_pdf',
            field=models.FileField(blank=True, null=True, upload_to='sheets/', verbose_name='fiche de réponses (PDF)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject_pdf',
            field=models.FileField(blank=True, null=True, upload_to='sheets/', verbose_name='sujet — questions (PDF)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='wrong_penalty',
            field=models.FloatField(default=0.0, help_text='Points retirés pour chaque mauvaise réponse QCM (0 = pas de pénalité)', verbose_name='pénalité par mauvaise réponse'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='reçu le'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="message d'erreur"),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='label',
            field=models.CharField(blank=True, max_length=120, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='processed_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='pages traitées'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='grader.quiz', verbose_name='épreuve'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de correction'), ('processing', 'Correction en cours'), ('done', 'Terminé'), ('error', 'Erreur')], default='done', max_length=12, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='total_pages',
            field=models.PositiveIntegerField(default=0, verbose_name='pages à traiter'),
        ),
        migrations.AlterField(
            model_name='scanbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='grader.scanbatch', verbose_name='lot'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='reçue le'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="message d'erreur"),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='id_read',
            field=models.CharField(blank=True, max_length=20, verbose_name="n° d'inscription lu"),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='image',
            field=models.ImageField(upload_to='scans/', verbose_name='image scannée'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='match_score',
            field=models.FloatField(default=0.0, verbose_name='score de rapprochement'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='name_crop',
            field=models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='zone du nom'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='ocr_name_raw',
            field=models.CharField(blank=True, max_length=200, verbose_name='nom lu (OCR)'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='overlay_image',
            field=models.ImageField(blank=True, null=True, upload_to='overlays/', verbose_name='image de contrôle'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='page_index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='page de la fiche'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="fichier d'origine"),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('ok', 'Lu avec succès'), ('no_markers', 'Repères non détectés'), ('no_match', 'Étudiant non identifié'), ('error', 'Erreur')], default='pending', max_length=12, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets', to='grader.student', verbose_name='étudiant'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='student_confirmed',
            field=models.BooleanField(default=False, verbose_name='identification confirmée'),
        ),
        migrations.AlterField(
            model_name='sheetscan',
            name='warped_image',
            field=models.ImageField(blank=True, null=True, upload_to='warped/', verbose_name='image redressée'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='grader.classgroup', verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=80, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, max_length=40, verbose_name="n° d'inscription"),
        ),
    ]
