# Generated by Django 5.2.18 on 2026-10-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0021_noms_en_minuscule'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duree',
            field=models.CharField(blank=True, help_text='Ex. « 1 h 30 » ou « ساعة ونصف ».', max_length=60, verbose_name="durée de l'épreuve"),
        ),
        migrations.AddField(
            model_name='quiz',
            name='entete',
            field=models.TextField(blank=True, help_text='Une ligne par ligne : ministère, établissement… Imprimé dans le cartouche du sujet.', verbose_name='en-tête du sujet'),
        ),
    ]
