# Generated by Django 5.2.18 on 2026-10-10 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0022_quiz_entete_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='note_admission',
            field=models.FloatField(blank=True, help_text="Sur le barème de l'épreuve (ex. 10 pour 10 / 20). Concours : note d'admission. Vide : pas de liste des admis.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='note minimale de réussite'),
        ),
    ]
