# Generated by Django 5.2.18 on 2026-10-11 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def titulaires(apps, schema_editor):
    """Le titulaire de chaque classe en devient l'un des enseignants : avant,
    l'accès suivait « owner » ; personne ne perd une classe à la mise à jour."""
    ClassGroup = apps.get_model("grader", "ClassGroup")
    for classe in ClassGroup.objects.exclude(owner=None):
        classe.enseignants.add(classe.owner_id)


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0023_quiz_note_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='classes_attribuees', to=settings.AUTH_USER_MODEL, verbose_name='enseignants'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to=settings.AUTH_USER_MODEL, verbose_name='créée par'),
        ),
        migrations.RunPython(titulaires, migrations.RunPython.noop),
    ]
